[package]
name = "ussc_web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = { version = "0.21.4", features = ["tokio-comp"] }
rocket = "0.5.0-rc.1"